name: Fetch StartGG Tournaments

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch: # Allow manual run from GitHub UI

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run fetch script
        env:
          STARTGG_TOKEN: ${{ secrets.STARTGG_TOKEN }}
        run: node sub/js/fetch-tournaments.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sub/data/tournaments.json
          git commit -m "Auto-update tournaments.json"
          git push
